#!/usr/bin/env bash
# description: Checks if the nodes' Mellanox Connect-4 firmware version is below the recommended version.

# Mellanox device IDs and minimum recommended firmware version
IDS="15b3:1015 15b3:1017 15b3:1013 15b3:101b"
MIN_VERS=16.28

# Source utility functions
[ -z "${UTILSFILE}" ] && source "$(dirname "${0}")/../utils"

# Check if the user has the necessary permissions
if oc auth can-i debug node >/dev/null 2>&1; then
  msg "Checking Mellanox firmware version (${BLUE}using oc debug, it can take a while${NOCOLOR})"
  fw_errors=0
  errors=0

  for node in $(oc get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{if eq .type "Ready"}}{{if eq .status "True"}}node/{{$node.metadata.name}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'); do
    ocdebugorwait # Pause for no OC debug running

    # Retrieve firmware versions
    if ! FIRMWAREVERS=$(oc debug --image="${OCDEBUGIMAGE}" "${node}" -- chroot /host sh -c "for id in ${IDS}; do for device in \$(lspci -D -d \"\${id}\" | awk '{ print \$1 }'); do echo -n \"\${device},\" ; ethtool -i \$(ls /sys/bus/pci/devices/\${device}/net/)|grep firmware-version|cut -d: -f2-|xargs echo|awk '{ print \$1 }';done;done" 2>/dev/null); then
      msg "${ORANGE}Error running oc debug in ${node}${NOCOLOR}"
    else
      if [ -n "${FIRMWAREVERS}" ]; then
        for result in ${FIRMWAREVERS}; do
          dev=$(echo "${result}" | awk -F, '{print $1}')
          fw=$(echo "${result}" | awk -F, '{print $2}' | awk -F. '{print $1"."$2}')
          
          # Check firmware version
          if [[ $(echo "${fw} < ${MIN_VERS}" | bc) -eq 1 ]]; then
            msg "Firmware for Mellanox card ${RED}${dev}${NOCOLOR} (${fw}) on ${RED}${node}${NOCOLOR} is below the minimum recommended version. Please upgrade to at least ${GREEN}${MIN_VERS}${NOCOLOR}."
            errors=$((errors + 1))
            fw_errors=$((fw_errors + 1))
            if [ -n "${ERRORFILE}" ]; then
              echo "${errors}" > "${ERRORFILE}"
            fi
          fi
        done
      else
        msg "Couldn't find Mellanox firmware version in ${node}"
      fi
    fi
  done

  if [[ $fw_errors -gt 0 ]]; then
    exit ${OCERROR}
  fi
  exit ${OCINFO}
else
  msg "Couldn't debug nodes, check permissions"
  exit ${OCSKIP}
fi

exit ${OCUNKNOWN}