#!/usr/bin/env bash
# description: Checks if there are not running pods

[ -z ${UTILSFILE} ] && source "$(dirname "${0}")/../utils"

error=false
errors=0  # Initialize errors variable

if oc auth can-i get pods -A >/dev/null 2>&1; then
  # Get all non-running pods with headers even if they are not found
  notrunning=$(oc get pods -A --field-selector=status.phase!=Running,status.phase!=Succeeded --ignore-not-found=true)
  HEADER=$(echo "${notrunning}" | head -n1)
  PODS=$(echo "${notrunning}" | tail -n +2)

  if [[ -n ${PODS} ]]; then
    msg "Pods not running ($(echo "${PODS}" | wc -l)):\n${HEADER}\n${RED}${PODS}${NOCOLOR}"
    errors=$((errors + 1))  # Correctly increment errors
    error=true
  fi

  if [[ -n ${ERRORFILE} ]]; then
    echo "${errors}" >${ERRORFILE}
  fi

  if [[ $error == true ]]; then
    exit ${OCERROR}
  else
    exit ${OCOK}
  fi

else
  msg "Couldn't get all pods, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKNOWN}