#!/usr/bin/env bash
# description: Checks if there are pods terminating

[ -z ${UTILSFILE} ] && source "$(dirname "${0}")/../utils"

error=false
errors=0  # Initialize errors variable

if oc auth can-i get pods -A >/dev/null 2>&1; then
  terminating_pods=$(oc get pods -A | grep -c 'Terminating')
  if [[ $terminating_pods -ge 1 ]]; then
    TERMPODS=$(oc get pods -A | grep 'Terminating')
    msg "Pods in Terminating state ($terminating_pods):\n${RED}${TERMPODS}${NOCOLOR}"
    errors=$((errors + 1))  # Correctly increment errors
    error=true
  fi
  if [[ -n ${ERRORFILE} ]]; then
    echo "${errors}" >${ERRORFILE}
  fi
  if [[ $error == true ]]; then
    exit ${OCERROR}
  else
    exit ${OCOK}
  fi
else
  msg "Couldn't get all pods, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKNOWN}