{
 "title": "IBM Fusion Fleet Dashboard 2.12.1",
 "tags": [
  "IBM Fusion",
  "v2.12.1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fleet Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "isf_cluster_details", "legendFormat": "__auto" },
    {
     "expr": "sum by (cluster) (1 - isf_service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(isf_nodes_info{name!=\"\", cluster!=\"\"} > 1) by (cluster) or \n(0 * count(isf_nodes_info{name!=\"\", cluster!=\"\"}) by (cluster))\n# creates a zero value for each cluster that has nodes",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(isf_environment_risk) by (cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (cluster) (isf_switches_info == 0) or \n(0 * count by (cluster) (isf_switches_info))\n#  return 0 for each cluster that has switches, indicating that all switches in those clusters are healthy.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fusion Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (service_name) (1 - isf_service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Foundation (NooBa) storage cluster health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by (cluster) (NooBaa_health_status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Global Data Platform (Remote Mount) storage cluster health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by(cluster) (max_over_time(gpfs_health_status[15m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Foundation (Ceph) storage cluster health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 337 },
     "targets": [
      {
       "expr": "sum by (cluster) (ceph_health_status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node with Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "# Count of nodes per cluster with value > 1 (Warning/Critical/Failed)\nsum by (cluster) (\n  max by (cluster, name) (\n    isf_nodes_info > bool 1\n  )\n)\n",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Switches with Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "# Count of switches per cluster where value == 0 (unhealthy)\nsum by (cluster) (\n  max by (cluster, name) (\n    isf_switches_info == bool 0\n  )\n)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Environmental and Upgrade Risks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Environmental risks per cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by (cluster) (isf_environment_risk)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Service upgrade risk count per cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (cluster) (isf_service_upgrade_risk_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node upgrade risk count per cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 307 },
     "targets": [
      {
       "expr": "sum by (cluster) (isf_node_upgrade_risk_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Switch upgrade risk count per cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 307 },
     "targets": [
      {
       "expr": "sum by (cluster) (isf_switch_upgrade_risk_count)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fusion Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Events per EventID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (shortname) (increase(fusion_events_total{severity=\"CRITICAL\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Critical Events per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (cluster) (increase(fusion_events_total{severity=\"CRITICAL\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warning Event per EventID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "sum by (shortname) (increase(fusion_events_total{severity=\"WARNING\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warning Event per Cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "sum by (cluster) (increase(fusion_events_total{severity=\"WARNING\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (%) per Switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "# This query calculates memory usage % for each SNMP exporter target.\n# The label_replace() removes the \"snmp-exporter-\" prefix from the `service` label\nlabel_replace(\n  ((memTotalReal - memAvailReal) / (memTotalReal)) * 100,\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "CPU Usage (%) per Switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "# Calculates CPU usage (% busy) for each service.\n# ssCpuIdle reports the percentage of time the CPU was idle.\n# Therefore, (100 - ssCpuIdle) gives the percentage of CPU currently in use.\n# label_replace() removes the \"snmp-exporter-\" prefix from the service label\n\nlabel_replace(\n  (100 - ssCpuIdle),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)\n",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Operational status of the interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "label_replace(\n  ifOperStatus,\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "({{ifName}}) {{service}}"
      }
     ]
    },
    {
     "title": "Power Source Units Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(\n  (psu1TempOrAmbientTemp/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "psu1-{{service}}"
      },
      {
       "expr": "label_replace(\n  (psu2Temp / 10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "psu2-{{service}}"
      }
     ]
    },
    {
     "title": "CPU Cores Temperature (High Speed Switch)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(\n  (cpuCoreSensor0/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "cpu0-{{service}}"
      },
      {
       "expr": "label_replace(\n  (cpuCoreSensor1/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "cpu1-{{service}}"
      }
     ]
    },
    {
     "title": "Ports, Board & ASIC Temperature (High Speed Switch)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(\n  (portAmbientSensor/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "ports-{{service}}"
      },
      {
       "expr": "label_replace(\n  (mainBoardAmbientSensor/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "board-{{service}}"
      },
      {
       "expr": "label_replace(\n  (asicTempSensor/10),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "asic-{{service}}"
      }
     ]
    },
    {
     "title": "Incoming packets count to each port",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n  irate(ifInOctets[10m]),\n  \"service\", \"$1\",\n  \"service\", \"^snmp-exporter-(.*)$\"\n)",
       "legendFormat": "({{ifAlias}}) {{service}}"
      }
     ]
    }
   ]
  }
 ]
}