{
 "title": "IBM Fusion Fleet Dashboard 2.12",
 "tags": [
  "IBM Fusion",
  "v2.12"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fleet Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "isf_cluster_details", "legendFormat": "__auto" },
    {
     "expr": "sum by (cluster) (1 - isf_service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(isf_nodes_info{name!=\"\", cluster!=\"\"} > 1) by (cluster) or \n(0 * count(isf_nodes_info{name!=\"\", cluster!=\"\"}) by (cluster))\n# creates a zero value for each cluster that has nodes",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(isf_environment_risk) by (cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (cluster) (isf_switches_info == 0) or \n(0 * count by (cluster) (isf_switches_info))\n#  return 0 for each cluster that has switches, indicating that all switches in those clusters are healthy.",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fusion Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Service Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service_name) (1 - isf_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Foundation (NooBa) storage cluster health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (cluster) (NooBaa_health_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Data Platform (Remote Mount) storage cluster health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(cluster) (max_over_time(gpfs_health_status[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Foundation (Ceph) storage cluster health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cluster) (ceph_health_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fusion Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Critical Events per EventID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (shortname) (increase(fusion_events_total{severity=\"CRITICAL\"}[10m])) + sum by (shortname) (increase(fusion_duplicate_events_total{severity=\"CRITICAL\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Events per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (cluster) (increase(fusion_events_total{severity=\"CRITICAL\"}[10m])) + sum by (cluster) (increase(fusion_duplicate_events_total{severity=\"CRITICAL\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning Event per EventID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (shortname) (increase(fusion_events_total{severity=\"WARNING\"}[10m])) + sum by (shortname) (increase(fusion_duplicate_events_total{severity=\"WARNING\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning Event per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (cluster) (increase(fusion_events_total{severity=\"WARNING\"}[10m])) + sum by (cluster) (increase(fusion_duplicate_events_total{severity=\"WARNING\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Environmental and Upgrade Risks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Environmental Risks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sum(isf_environment_risk)", "legendFormat": "Total risks" }
   ]
  },
  {
   "title": "Service upgrade risk count per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (cluster) (isf_service_upgrade_risk_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node upgrade risk count per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (cluster) (isf_node_upgrade_risk_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch upgrade risk count per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (cluster) (isf_switch_upgrade_risk_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Node with Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "count(count(isf_nodes_info{name!=\"\"} > 1) by (name)) or vector(0)\n# count of unique node names that have values greater than 1",
     "legendFormat": "Unhealthy Count"
    }
   ]
  },
  {
   "title": "Switches with Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "count(count(isf_switches_info{name!=\"\"} == 0) by (name)) or vector(0)\n# count unique unhealthy switches",
     "legendFormat": "Unhealthy count"
    }
   ]
  }
 ]
}