{{- if and .Values.platformKuadrant.enabled .Values.platformKuadrant.instance.enabled }}
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: {{ .Values.platformKuadrant.instance.name }}
  namespace: {{ .Values.platformKuadrant.namespace }}
  labels:
    {{- include "maas-platform.labels" . | nindent 4 }}
spec: {}
{{- end }}

{{- if and .Values.leaderWorkerSet.enabled .Values.leaderWorkerSet.instance.enabled }}
---
apiVersion: operator.openshift.io/v1
kind: LeaderWorkerSetOperator
metadata:
  name: {{ .Values.leaderWorkerSet.instance.name }}
  namespace: {{ .Values.leaderWorkerSet.namespace }}
  labels:
    {{- include "maas-platform.labels" . | nindent 4 }}
spec:
  managementState: {{ .Values.leaderWorkerSet.instance.managementState }}
{{- end }}