---
namespace: fusion-reference

secretGenerator:
- name: mysql-pass
  literals:
  - password=mypassword

resources:
- mysql.yaml
- fusion-reference.yaml

patches:
   # Patch the PVC .spec.storageClassName with cluster/block storage class value
  - target:
      kind: PersistentVolumeClaim
      name: wordpress-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
   # Patch the PVC .spec.storageClassName with cluster/block storage class value
  - target:
      kind: PersistentVolumeClaim
      name: mysql-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd 
   # Patch the route .spec.host with cluster/host value
  - target:
      kind: Route
      name: fusion-reference
    patch: |-
      - op: replace
        path: /spec/host
        value: fusion-reference-wp.apps.rdr-blue-svl-site-0.cp.fyre.ibm.com
