apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: minio-sync-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: minio
  groups:
    - name: minio-volumes
      type: volume
    - name: minio-resources
      type: resource
  hooks:
  - name: minio-deployment-check
    type: check
    namespace: ${GROUP.minio-resources.namespace}
    selectResource: deployment
    nameSelector: minio
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: minio-pod-exec
    type: exec
    namespace: ${GROUP.minio-resources.namespace}
    labelSelector: app=minio
    timeout: 60
    onError: fail
    ops:
    - name: "sync-filesystem"
      command: >
        ["/bin/bash", "-c", "sync -f /data/*"]
      container: minio
  workflows:
  - name: backup
    sequence:
    - group: minio-resources
    - hook: minio-pod-exec/sync-filesystem
    - group: minio-volumes
  - name: restore
    sequence:
    - group: minio-volumes
    - group: minio-resources
    - hook: minio-deployment-check/replicasReady
