apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.projectName }}-${{ values.environment }}
  title: "${{ values.projectName }} (${{ values.environment }})"
  description: >
    OpenShift namespace for the ${{ values.projectName }} project
    (${{ values.environment }} environment), provisioned via IBM Fusion NaaS.
  annotations:
    github.com/project-slug: ${{ values.repoOrg }}/${{ values.repoName }}
    backstage.io/source-location: >
      url:${{ values.githubBaseUrl }}/${{ values.repoOrg }}/${{ values.repoName }}/blob/${{ values.targetBranch }}/namespaces/${{ values.projectName }}-${{ values.environment }}/catalog-info.yaml
    openshift.io/display-name: "${{ values.projectName }}-${{ values.environment }}"
  links:
    - title: OpenShift Console
      url: ${{ values.consoleBaseUrl }}/k8s/cluster/namespaces/${{ values.projectName }}-${{ values.environment }}
      icon: dashboard
    {%- if values.applicationName %}
    - title: ArgoCD Application
      url: ${{ values.argocdBaseUrl }}/applications/${{ values.applicationName }}-${{ values.environment }}
      icon: dashboard
    {%- endif %}
  labels:
    business-unit: ${{ values.businessUnit }}
    environment: ${{ values.environment }}
    project: ${{ values.projectName }}
    size: ${{ values.size }}
  tags:
    - namespace
    - openshift
    - naas
    - ${{ values.environment }}
    {%- if values.applicationName %}
    - ${{ values.applicationName }}
    {%- endif %}
spec:
  type: openshift-namespace
  owner: ${{ values.catalogOwner }}
  lifecycle: ${{ values.environment }}
  system: ${{ values.catalogSystem }}
