apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: ${{ values.projectName }}-${{ values.environment }}
spec:
  hard:
    {%- if values.size == "small" %}
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    count/pods: "20"
    count/services: "10"
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    {%- elif values.size == "medium" %}
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    count/pods: "40"
    count/services: "20"
    requests.storage: 200Gi
    persistentvolumeclaims: "20"
    {%- else %}
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    count/pods: "100"
    count/services: "50"
    requests.storage: 500Gi
    persistentvolumeclaims: "50"
    {%- endif %}
