{
 "title": "ISF Compute Dashboard 2.0",
 "description": "The new redesigned compute dashboard for storage fusion.",
 "tags": [ "isf-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Gauge Summary for each Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Consumed by the CPU",
   "type": "gauge",
   "description": "Note: For threshold color change, an average value of 205W is set based on the Thermal Design Power (TDP) from multiple specs. Actual value may differ for each model. Kindly refer the hardware spec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "compute_energy_stats_in_watts{energyStatsInWatts=\"CPU\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "compute_energy_stats_in_watts{energyStatsInWatts=\"Server\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Energy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Energy Consumption - CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "compute_energy_stats_in_watts{energyStatsInWatts=\"CPU\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Energy Consumption - Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "compute_energy_stats_in_watts{energyStatsInWatts=\"Server\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Thermal Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Thermal Stats - CPU 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "compute_thermal_Stats_in_celcius{thermalStatInCelcius=\"CPU 1\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Thermal Stats - CPU 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "compute_thermal_Stats_in_celcius{thermalStatInCelcius=\"CPU 2\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Thermal Stats - Ambient",
   "type": "graph",
   "description": "Ambient is the temperature outside the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "compute_thermal_Stats_in_celcius{thermalStatInCelcius=\"Ambient\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Thermal Stats - Exhaust",
   "type": "graph",
   "description": "Exhaust is temperature at rear end where fans are spinning.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "compute_thermal_Stats_in_celcius{thermalStatInCelcius=\"Exhaust\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}