{
 "title": "ISF_Storage_Dashboard",
 "tags": [ "isf-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    { "expr": "fs_read_throughput" },
    { "expr": "fs_write_throughput" }
   ]
  },
  {
   "title": "Disk Read Time",
   "type": "graph",
   "description": "Disk Read Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_read_time_seconds_total"
    }
   ]
  },
  {
   "title": "Write IOPs",
   "type": "graph",
   "description": "Write IOPs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "IOPs" }
   ],
   "targets": [
    { "expr": "write_operations" }
   ]
  },
  {
   "title": "Read IOPs",
   "type": "graph",
   "description": "Read IOPs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "IOPs" }
   ],
   "targets": [
    { "expr": "read_operations" }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "description": "Disk Capacity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    { "expr": "disk_capacity" }
   ]
  }
 ]
}