{
 "title": "ISF_Network_Dashboard",
 "tags": [ "isf-dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Service",
    "query": "label_values(up{job=~\"snmp-exporter\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total memory",
   "type": "stat",
   "description": "The total amount of real/physical memory installed on this host",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "memTotalReal{service=\"$node\"}"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "description": "The amount of real/physical memory currently unused or available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memAvailReal{service=\"$node\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System CPU",
   "type": "graph",
   "description": "The percentage of CPU time spent processing system-level code, calculated over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuSystem{service=\"$node\"}"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "graph",
   "description": "The percentage of CPU time spent processing user-level code, calculated over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuUser{service=\"$node\"}"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "description": "The percentage of processor time spent idle, calculated over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuIdle{service=\"$node\"}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "PSU1 Temperature",
   "type": "gauge",
   "description": "This is PSU1 temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(psu1TempOrAmbientTemp{service=\"$node\"})/10"
    },
    {}
   ]
  },
  {
   "title": "PSU2 Temperature",
   "type": "gauge",
   "description": "This is PSU2 temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psu2Temp{service=\"$node\"}/10"
    },
    {}
   ]
  },
  {
   "title": "CPU Package Temperature",
   "type": "gauge",
   "description": "This is cpu package temerature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cpuPackageSensor{service=\"$node\"})/10"
    }
   ]
  },
  {
   "title": "ASIC Temperature",
   "type": "gauge",
   "description": "This is asic temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asicTempSensor{service=\"$node\"}/10"
    }
   ]
  },
  {
   "title": "CPU Core Sensor 0",
   "type": "gauge",
   "description": "This is cpu core sensor 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuCoreSensor0{service=\"$node\"}/10"
    }
   ]
  },
  {
   "title": "CPU Core Sensor 1",
   "type": "gauge",
   "description": "This is cpu core sensor 1",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuCoreSensor1{service=\"$node\"}/10"
    }
   ]
  },
  {
   "title": "Port Ambient Sensor ",
   "type": "gauge",
   "description": "This is port ambient sensor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portAmbientSensor{service=\"$node\"}/10"
    }
   ]
  },
  {
   "title": "Main Board Sensor ",
   "type": "gauge",
   "description": "This is main board ambient sensor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mainBoardAmbientSensor{service=\"$node\"}/10"
    }
   ]
  },
  { "title": "Interface Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Input Octects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifInOctets{service=\"$node\"}[10m])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Output Octects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutOctets{service=\"$node\"}[10m])",
     "legendFormat": "{{ifIndex}}"
    }
   ]
  }
 ]
}