{
 "title": "Job Tracking",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "label_values(job_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(idp_job_duration_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Timings Overview",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(idp_job_duration_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Total Job Duration"
    },
    {
     "expr": "max_over_time(idp_kafka_message_lag{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Kafka Lag"
    },
    {
     "expr": "max_over_time(idp_inventory_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Inventory Time - {{volume_group}}"
    },
    {
     "expr": "max_over_time(idp_resource_group_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Resource Group Time"
    },
    {
     "expr": "max_over_time(idp_volume_group_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Volume Group Time"
    },
    {
     "expr": "max_over_time(idp_create_snapshot_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Create Snapshot Time - {{pvc_name}}"
    },
    {
     "expr": "max_over_time(idp_data_transfer_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Data Transfer Time"
    },
    {
     "expr": "max_over_time(idp_hook_execution_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Hook Execution Time - {{recipe_group}}"
    },
    {
     "expr": "max_over_time(idp_velero_backup_deletion_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Velero Backup Deletion Time"
    },
    {
     "expr": "max_over_time(idp_snapshot_backup_deletion_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Snapshot Backup Deletion Time"
    },
    {
     "expr": "max_over_time(idp_restic_backup_deletion_time_ms_sum{job_id=\"$job_id\"}[$__range])",
     "legendFormat": "Restic Backup Deletion Time"
    }
   ]
  },
  {
   "title": "Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Capacity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(idp_backup_capacity{job_id=\"$job_id\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total PVC Size",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(idp_total_pvc_size{job_id=\"$job_id\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of PVCs",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(idp_num_pvcs{job_id=\"$job_id\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}