{{- if .Values.operator.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-operator
  namespace: {{ include "operator.namespace" . }}
  labels:
    {{- include "vault-operator.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operator.subscription.channel }}
  name: vault-secrets-operator
  source: {{ .Values.operator.subscription.source }}
  sourceNamespace: {{ .Values.operator.subscription.sourceNamespace }}
  installPlanApproval: {{ .Values.operator.subscription.installPlanApproval }}
  {{- if .Values.operator.subscription.startingCSV }}
  startingCSV: {{ .Values.operator.subscription.startingCSV }}
  {{- end }}
{{- end }}

# Made with Bob
