apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: maximo-optimizer-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: maximo-optimizer
  groups:
  - name: maximo-optimizer-volumes
    type: volume
  - name: maximo-optimizer-resources
    type: resource
    includedResourceTypes:
      - optimizerapps.apps.mas.ibm.com
      - optimizerworkspaces.apps.mas.ibm.com
      - secrets 
      - operatorgroups
      - subscriptions
    labelSelector: for-backup=true 
  - name: restore-maximo-optimizer-secrets
    backupRef: maximo-optimizer-resources
    type: resource
    includedResourceTypes:
      - secrets
  - name: restore-maximo-optimizer-operatorgroups
    backupRef: maximo-optimizer-resources
    type: resource
    includedResourceTypes:
      - operatorgroups
  - name: restore-maximo-optimizer-subscriptions
    backupRef: maximo-optimizer-resources
    type: resource
    includedResourceTypes:
      - subscriptions
  - name: restore-maximo-optimizer-optimizerapps-optimizerworkspaces
    backupRef: maximo-optimizer-resources
    type: resource
    includedResourceTypes:
      - optimizerapps.apps.mas.ibm.com
      - optimizerworkspaces.apps.mas.ibm.com
  hooks:
  - name: maximo-optimizer-ibm-mas-operator-check
    type: check
    namespace: ${GROUP.maximo-optimizer-resources.namespace}
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-mas-optimizer.mas-${MAS_INSTANCE_ID}-optimizer=
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: maximo-optimizer-ibm-truststore-mgr-controller-manager-check
    type: check
    namespace: ${GROUP.maximo-optimizer-resources.namespace}
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-truststore-mgr.mas-${MAS_INSTANCE_ID}-optimizer= 
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: maximo-optimizer-optimizerapps-check
    type: check
    namespace: ${GROUP.maximo-optimizer-resources.namespace} 
    selectResource: apps.mas.ibm.com/v1/optimizerapps
    labelSelector: for-backup=true 
    timeout: 7200
    onError: fail
    chks:
    - name: statusReady
      timeout: 7200
      onError: fail
      condition: "{$.status.conditions[?(@.type==\"Ready\")].status} == {\"True\"}"
  - name: maximo-optimizer-optimizerworkspaces-check
    type: check
    namespace: ${GROUP.maximo-optimizer-resources.namespace} 
    selectResource: apps.mas.ibm.com/v1/optimizerworkspaces
    labelSelector: for-backup=true 
    timeout: 7200
    onError: fail
    chks:
    - name: statusReady
      timeout: 7200
      onError: fail
      condition: "{$.status.conditions[?(@.type==\"Ready\")].status} == {\"True\"}"
  - name: ibm-mas-optimizer-operator-exec
    labelSelector: app.kubernetes.io/instance=ibm-mas-optimizer
    namespace: ${GROUP.maximo-optimizer-resources.namespace}
    onError: fail
    ops:
    - command: |
        ["/bin/bash", "-c", "sleep 300"]
      container: manager
      name: sleep-five-minutes
      timeout: 600
    selectResource: pod
    timeout: 180
    type: exec
  workflows:
  - name: backup
    sequence:
    - group: maximo-optimizer-resources
    - group: maximo-optimizer-volumes
  - name: restore
    sequence:
    - group: maximo-optimizer-volumes
    - group: restore-maximo-optimizer-secrets
    - group: restore-maximo-optimizer-operatorgroups
    - group: restore-maximo-optimizer-subscriptions
    - hook: maximo-optimizer-ibm-mas-operator-check/replicasReady
    - hook: maximo-optimizer-ibm-truststore-mgr-controller-manager-check/replicasReady
    - hook: ibm-mas-optimizer-operator-exec/sleep-five-minutes
    - group: restore-maximo-optimizer-optimizerapps-optimizerworkspaces
    - hook: maximo-optimizer-optimizerapps-check/statusReady
    - hook: maximo-optimizer-optimizerworkspaces-check/statusReady
