apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/<your-username>/storage-fusion.git
    targetRevision: main
    path: AI/fusion-openshift-ai/gitops/rhoai

  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

