{{- if .Values.operator.enabled }}
{{- if .Values.operator.createExternalSecretsConfig }}
---
apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
  labels:
    {{- include "external-secrets-operator.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "2"
spec:
  {{- if .Values.operator.externalSecretsConfig }}
  {{- toYaml .Values.operator.externalSecretsConfig | nindent 2 }}
  {{- else }}
  # Use operator defaults
  {}
  {{- end }}
{{- end }}
{{- end }}

# Made with Bob