apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: db2u-instance-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: db2uinstance
  groups:
  - name: db2u-volumes
    type: volume
  - excludedResourceTypes:
    - clusterserviceversions
    - subscriptions.operators.coreos.com
    - formations.db2u.databases.ibm.com
    - db2uengines.db2u.databases.ibm.com
    - db2uinstances.db2u.databases.ibm.com
    - pods
    - replicasets
    - statefulsets
    name: db2u-resources
    type: resource
  - includedResourceTypes:
    - operatorgroups
    name: db2u-operatorgroups
    type: resource
  - includedResourceTypes:
    - subscriptions.operators.coreos.com
    name: db2u-subscriptions
    type: resource
  - includedResourceTypes:
    - db2uinstances.db2u.databases.ibm.com
    name: db2u-db2uinstances
    type: resource
  hooks:
  - chks:
    - condition: '{$.status.state} == {"Ready"}'
      name: stateReady
      onError: fail
      timeout: 600
    labelSelector: type=engine,component=db2wh,formation_type=db2wh
    name: db2uengine-check
    namespace: ${GROUP.db2u-volumes.namespace}
    onError: fail
    selectResource: db2u.databases.ibm.com/v1alpha1/db2uengines
    timeout: 120
    type: check
  - chks:
    - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
      name: replicasReady
      onError: fail
      timeout: 600
    labelSelector: olm.owner.kind=ClusterServiceVersion
    name: db2u-operator-check
    namespace: ${GROUP.db2u-volumes.namespace}
    onError: fail
    selectResource: deployment
    timeout: 120
    type: check
  - chks:
    - condition: '{$.status.state} == {"Ready"}'
      name: stateReady
      onError: fail
      timeout: 900
    name: db2uinstance-check
    labelSelector: for-backup=true
    namespace: ${GROUP.db2u-volumes.namespace}
    onError: fail
    selectResource: db2u.databases.ibm.com/v1/db2uinstances
    timeout: 800
    type: check
  - labelSelector: name=dashmpp-head-0
    name: db2uinstances-pod-exec
    namespace: ${GROUP.db2u-volumes.namespace}
    onError: fail
    ops:
    - command: |
        ["/bin/bash", "-c", "manage_snapshots --action suspend --retry 3"]
      container: db2u
      name: suspend
    - command: |
        ["/bin/bash", "-c", "manage_snapshots --action resume --retry 3"]
      container: db2u
      name: resume
    - command: |
        ["/bin/bash", "-c", "manage_snapshots --action restore --retry 3"]
      container: db2u
      name: restore
      timeout: 300
    selectResource: pod
    timeout: 300
    type: exec
  - labelSelector: control-plane=db2u-operator-manager
    name: db2u-operator-manager-exec
    namespace: ${GROUP.db2u-volumes.namespace}
    onError: fail
    ops:
    - command: |
        ["/bin/bash", "-c", "db2uinstances=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uinstances | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2uinstance in $db2uinstances; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uinstances/$db2uinstance?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":\"true\"}}}'; done"]
      container: manager
      name: maintenance-mode-on
    - command: |
        ["/bin/bash", "-c", "db2uinstances=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uinstances | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2uinstance in $db2uinstances; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uinstances/$db2uinstance?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":null}}}'; done"]
      container: manager
      name: maintenance-mode-off
    - command: |
        ["/bin/bash", "-c", "db2uengines=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1alpha1/namespaces/${GROUP.db2u-volumes.namespace}/db2uengines | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2uengine in $db2uengines; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1alpha1/namespaces/${GROUP.db2u-volumes.namespace}/db2uengines/$db2uengine?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":\"true\"}}}'; done"]
      container: manager
      name: engine-maintenance-mode-on
    - command: |
        ["/bin/bash", "-c", "db2uengines=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1alpha1/namespaces/${GROUP.db2u-volumes.namespace}/db2uengines | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2uengine in $db2uengines; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1alpha1/namespaces/${GROUP.db2u-volumes.namespace}/db2uengines/$db2uengine?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":null}}}'; done"]
      container: manager
      name: engine-maintenance-mode-off
    - command: |
        ["/bin/bash", "-c", "sleep 300"]
      container: manager
      name: sleep-5-minutes
      timeout: 600
    selectResource: pod
    timeout: 120
    type: exec
  workflows:
  - failOn: any-error
    name: backup
    sequence:
    - hook: db2u-operator-manager-exec/maintenance-mode-on
    - hook: db2u-operator-manager-exec/engine-maintenance-mode-on
    - group: db2u-resources
    - group: db2u-operatorgroups
    - group: db2u-subscriptions
    - group: db2u-db2uinstances
    - hook: db2uinstances-pod-exec/suspend
    - group: db2u-volumes
    - hook: db2uinstances-pod-exec/resume
    - hook: db2u-operator-manager-exec/maintenance-mode-off
    - hook: db2u-operator-manager-exec/engine-maintenance-mode-off
  - failOn: any-error
    name: restore
    sequence:
    - group: db2u-operatorgroups
    - group: db2u-subscriptions
    - group: db2u-volumes
    - hook: db2u-operator-check/replicasReady
    - group: db2u-resources
    - hook: db2u-operator-manager-exec/sleep-5-minutes
    - group: db2u-db2uinstances
    - hook: db2u-operator-manager-exec/maintenance-mode-off
    - hook: db2u-operator-manager-exec/engine-maintenance-mode-off
    - hook: db2uengine-check/stateReady
    - hook: db2uinstances-pod-exec/restore
    - hook: db2uinstance-check/stateReady
