{{- if .Values.operators.openshiftAI.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: {{ .Values.operators.openshiftAI.namespace }}
  labels:
    {{- include "maas-operators.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operators.openshiftAI.channel }}
  installPlanApproval: {{ .Values.operators.openshiftAI.installPlanApproval }}
  name: rhods-operator
  source: {{ .Values.operators.openshiftAI.source }}
  sourceNamespace: {{ .Values.operators.openshiftAI.sourceNamespace }}
{{- end }}

{{- if .Values.operators.connectivityLink.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: {{ .Values.operators.connectivityLink.namespace }}
  labels:
    {{- include "maas-operators.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operators.connectivityLink.channel }}
  installPlanApproval: {{ .Values.operators.connectivityLink.installPlanApproval }}
  name: rhcl-operator
  source: {{ .Values.operators.connectivityLink.source }}
  sourceNamespace: {{ .Values.operators.connectivityLink.sourceNamespace }}
{{- end }}

{{- if .Values.operators.certManager.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: {{ .Values.operators.certManager.namespace }}
  labels:
    {{- include "maas-operators.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operators.certManager.channel }}
  installPlanApproval: {{ .Values.operators.certManager.installPlanApproval }}
  name: openshift-cert-manager-operator
  source: {{ .Values.operators.certManager.source }}
  sourceNamespace: {{ .Values.operators.certManager.sourceNamespace }}
{{- end }}

{{- if .Values.operators.leaderWorkerSet.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: leader-worker-set
  namespace: {{ .Values.operators.leaderWorkerSet.namespace }}
  labels:
    {{- include "maas-operators.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operators.leaderWorkerSet.channel }}
  installPlanApproval: {{ .Values.operators.leaderWorkerSet.installPlanApproval }}
  name: leader-worker-set
  source: {{ .Values.operators.leaderWorkerSet.source }}
  sourceNamespace: {{ .Values.operators.leaderWorkerSet.sourceNamespace }}
{{- end }}

{{- if false }}
{{- if .Values.operators.grafana.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: {{ .Values.operators.grafana.namespace }}
  labels:
    {{- include "maas-operators.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operators.grafana.channel }}
  installPlanApproval: {{ .Values.operators.grafana.installPlanApproval }}
  name: grafana-operator
  source: {{ .Values.operators.grafana.source }}
  sourceNamespace: {{ .Values.operators.grafana.sourceNamespace }}
{{- end }}
{{- end }}