apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: maximo-db2-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: db2ucluster
  groups:
    - name: db2u-volumes
      type: volume
    - name: db2u-cluster-resources
      type: resource
      includeClusterResources: true
      includedResourceTypes:
        - customresourcedefinitions
        - clusterroles
        - clusterrolebindings
      labelSelector: operators.coreos.com/db2u-operator.${DB2_NAMESPACE}=
    - name: db2u-resources
      type: resource
      excludedResourceTypes:
        - clusterserviceversions
        - pods 
  hooks:
  - name: db2u-operator-check
    type: check
    namespace: ${GROUP.db2u-volumes.namespace}
    selectResource: deployment
    labelSelector: operators.coreos.com/db2u-operator.${DB2_NAMESPACE}=
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: db2ucluster-check
    type: check
    namespace: ${GROUP.db2u-volumes.namespace}
    selectResource: db2u.databases.ibm.com/v1/db2uclusters
    labelSelector: for-backup=true
    timeout: 1200
    onError: fail
    chks:
    - name: stateReady
      timeout: 1200
      onError: fail
      condition: "{$.status.state} == {\"Ready\"}"
  - name: db2uclusters-pod-exec
    type: exec
    namespace: ${GROUP.db2u-volumes.namespace}
    labelSelector: name=dashmpp-head-0
    timeout: 300
    onError: fail
    ops:
    - name: "suspend"
      command: >
        ["manage_snapshots --action suspend --retry 3"]
      container: db2u
    - name: "resume"
      command: >
        ["manage_snapshots --action resume --retry 3"]
      container: db2u
    - name: "restore"
      command: >
        ["manage_snapshots --action restore --retry 3"]
      container: db2u
      timeout: 300
  - name: db2u-operator-manager-exec
    type: exec
    namespace: ${GROUP.db2u-volumes.namespace}
    labelSelector: control-plane=db2u-operator-manager
    timeout: 120
    onError: fail
    ops:
    - name: "maintenance-mode-on"
      command: |
        ["/bin/bash", "-c", "db2uclusters=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uclusters | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2ucluster in $db2uclusters; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uclusters/$db2ucluster?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":\"true\"}}}'; done"]
      container: manager
    - name: "maintenance-mode-off"
      command: |
        ["/bin/bash", "-c", "db2uclusters=$(curl -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Accept: application/yaml' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uclusters | grep '^    name: ' | tr -d ' ' | cut -c 6-); for db2ucluster in $db2uclusters; do curl -X PATCH --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`\" -H 'Content-Type: application/merge-patch+json' -H 'Accept: application/json' -k https://kubernetes.default.svc/apis/db2u.databases.ibm.com/v1/namespaces/${GROUP.db2u-volumes.namespace}/db2uclusters/$db2ucluster?fieldManager=kubectl-annotate -d '{\"metadata\":{\"annotations\":{\"db2u.databases.ibm.com/maintenance-pause-reconcile\":null}}}'; done"]
      container: manager
  workflows:
  - name: backup
    sequence:
    - hook: db2u-operator-manager-exec/maintenance-mode-on
    - group: db2u-cluster-resources
    - group: db2u-resources
    - hook: db2uclusters-pod-exec/suspend
    - group: db2u-volumes
    - hook: db2uclusters-pod-exec/resume
    - hook: db2u-operator-manager-exec/maintenance-mode-off
  - name: restore
    sequence:
    - group: db2u-cluster-resources
    - group: db2u-volumes
    - group: db2u-resources
    - hook: db2u-operator-check/replicasReady
    - hook: db2u-operator-manager-exec/maintenance-mode-off
    - hook: db2ucluster-check/stateReady
    - hook: db2uclusters-pod-exec/restore
