{
 "title": "IBM Fusion Fleet Dashboard",
 "tags": [
  "IBM Fusion",
  "v2.11"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fleet Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "isf_cluster_details", "legendFormat": "__auto" },
    {
     "expr": "sum by (cluster) (1 - isf_service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(isf_nodes_info{name!=\"\", cluster!=\"\"} > 1) by (cluster) or \n(0 * count(isf_nodes_info{name!=\"\", cluster!=\"\"}) by (cluster))\n# creates a zero value for each cluster that has nodes",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(isf_environment_risk) by (cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (cluster) (isf_switches_info == 0) or \n(0 * count by (cluster) (isf_switches_info))\n#  return 0 for each cluster that has switches, indicating that all switches in those clusters are healthy.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service_name) (1 - isf_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Environmental Risks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(isf_environment_risk)", "legendFormat": "Total risks" }
   ]
  },
  {
   "title": "Node with Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(count(isf_nodes_info{name!=\"\"} > 1) by (name)) or vector(0)\n# count of unique node names that have values greater than 1",
     "legendFormat": "Unhealthy Count"
    }
   ]
  },
  {
   "title": "Switches with Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(count(isf_switches_info{name!=\"\"} == 0) by (name)) or vector(0)\n# count unique unhealthy switches",
     "legendFormat": "Unhealthy count"
    }
   ]
  }
 ]
}