apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: mongodb-community-standalone-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: mongodb
  groups:
    - name: mongodb-volumes
      type: volume
      includedNamespaces:
        - mongodb
    - name: mongodb-resources
      type: resource
      includedNamespaces:
        - mongodb
      includeClusterResources: true
      excludedResourceTypes:
        - events
        - mongodbs.opstreelabs.in
    - name: mongodb-instances
      type: resource
      includedNamespaces:
        - mongodb
      includedResourceTypes:
        - mongodbs.opstreelabs.in
  hooks:
  - name: mongodb-operator-check
    type: check
    namespace: mongodb
    selectResource: deployment
    labelSelector: control-plane=mongodb-operator
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 180
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: mongodb-standalone-check
    type: check
    namespace: mongodb
    selectResource: statefulset
    labelSelector: app=mongodb-standalone,mongodb_setup=standalone,role=standalone
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 180
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: mongodb-standalone-exec
    labelSelector: app=mongodb-standalone
    timeout: 300
    namespace: mongodb
    onError: fail
    ops:
      - command: >
          ["/bin/bash", "-c", "mongosh -u `printenv MONGO_ROOT_USERNAME` -p `printenv MONGO_ROOT_PASSWORD` --eval \"db.fsyncLock()\""]
        container: mongo
        timeout: 300
        name: fsyncLock
        onError: fail
      - command: >
          ["/bin/bash", "-c", "mongosh -u `printenv MONGO_ROOT_USERNAME` -p `printenv MONGO_ROOT_PASSWORD` --eval \"db.fsyncUnlock()\""]
        container: mongo
        timeout: 300
        name: fsyncUnlock
        onError: fail
    selectResource: pod
    type: exec
  workflows:
  - name: backup
    sequence:
    - group: mongodb-resources
    - group: mongodb-instances
    - hook: mongodb-standalone-exec/fsyncLock
    - group: mongodb-volumes
    - hook: mongodb-standalone-exec/fsyncUnlock
  - name: restore
    sequence:
    - group: mongodb-volumes
    - group: mongodb-resources
    - hook: mongodb-operator-check/replicasReady
    - group: mongodb-instances
    - hook: mongodb-standalone-check/replicasReady
