{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  labels:
    {{- include "fusion-gitops.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
{{- end }}

# Made with Bob