apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: neo4j_cluster_backup_restore_recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: neo4j
  groups:
    - name: neo4j_volumes
      type: volume
    - name: neo4j_resources
      type: resource
      excludedResourceTypes:
        - pods
  hooks:
  - name: neo4j_core_statefulset_check
    type: check
    namespace: ${GROUP.neo4j_resources.namespace}
    selectResource: statefulset
    labelSelector: app.kubernetes.io/component=core
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: neo4j_replica_statefulset_check
    type: check
    namespace: ${GROUP.neo4j_resources.namespace}
    selectResource: statefulset
    labelSelector: app.kubernetes.io/component=replica
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"      
  - name: neo4j_pod_exec
    type: exec
    namespace: ${GROUP.neo4j_resources.namespace}
    nameSelector: $REPLACE_WRITER_POD_NAME
    timeout: 120
    onError: fail
    ops:
    - name: disable_write
      command: "cypher-shell -u neo4j -p $NEO4J_SECRETS_PASSWORD \"CALL dbms.setConfigValue('dbms.databases.default_to_read_only', 'true');\""
      container: neo4j-cluster-neo4j
      timeout: 120 
    - name: enable_write
      command: "cypher-shell -u neo4j -p $NEO4J_SECRETS_PASSWORD \"CALL dbms.setConfigValue('dbms.databases.default_to_read_only', 'false');\""
      container: neo4j-cluster-neo4j
      timeout: 120          
  workflows:
  - name: backup
    sequence:
    - group: neo4j_resources
    - hook: neo4j_pod_exec/disable_write
    - group: neo4j_volumes
    - hook: neo4j_pod_exec/enable_write
  - name: restore
    sequence:
    - group: neo4j_volumes
    - group: neo4j_resources
    - hook: neo4j_core_statefulset_check/replicasReady
    - hook: neo4j_replica_statefulset_check/replicasReady
