{{- if and .Values.operator.enabled .Values.secretStores.aws.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStores.aws.name }}
  labels:
    {{- include "external-secrets-operator.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "2"
    "helm.sh/resource-policy": keep
spec:
  provider:
    aws:
      service: {{ .Values.secretStores.aws.service }}
      region: {{ .Values.secretStores.aws.region }}
      {{- if eq .Values.secretStores.aws.auth.method "credentials" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStores.aws.auth.credentials.accessKeyIDSecretRef.name }}
            key: {{ .Values.secretStores.aws.auth.credentials.accessKeyIDSecretRef.key }}
            namespace: {{ .Values.secretStores.aws.auth.credentials.accessKeyIDSecretRef.namespace }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretStores.aws.auth.credentials.secretAccessKeySecretRef.name }}
            key: {{ .Values.secretStores.aws.auth.credentials.secretAccessKeySecretRef.key }}
            namespace: {{ .Values.secretStores.aws.auth.credentials.secretAccessKeySecretRef.namespace }}
      {{- else if eq .Values.secretStores.aws.auth.method "irsa" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStores.aws.auth.irsa.serviceAccountRef.name }}
            namespace: {{ .Values.secretStores.aws.auth.irsa.serviceAccountRef.namespace }}
      {{- end }}
{{- end }}

# Made with Bob
