{{- if and .Values.operator.enabled .Values.secretStores.ibmCloud.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStores.ibmCloud.name }}
  labels:
    {{- include "external-secrets-operator.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "2"
    "helm.sh/resource-policy": keep
spec:
  provider:
    ibm:
      serviceUrl: {{ .Values.secretStores.ibmCloud.serviceUrl | quote }}
      {{- if eq .Values.secretStores.ibmCloud.auth.method "apiKey" }}
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: {{ .Values.secretStores.ibmCloud.auth.apiKey.secretRef.name }}
            key: {{ .Values.secretStores.ibmCloud.auth.apiKey.secretRef.key }}
            namespace: {{ .Values.secretStores.ibmCloud.auth.apiKey.secretRef.namespace }}
      {{- else if eq .Values.secretStores.ibmCloud.auth.method "containerAuth" }}
      auth:
        containerAuth:
          profile: {{ .Values.secretStores.ibmCloud.auth.containerAuth.profile | quote }}
          tokenLocation: {{ .Values.secretStores.ibmCloud.auth.containerAuth.tokenLocation | quote }}
      {{- end }}
{{- end }}

# Made with Bob
