apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: minio-scale-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns
spec:
  appType: minio
  groups:
    - name: minio-volumes
      type: volume
    - name: minio-resources
      type: resource
  hooks:
  - name: minio-deployment-check
    type: check
    namespace: ${GROUP.minio-resources.namespace}
    selectResource: deployment
    nameSelector: minio
    timeout: 120
    onError: fail
    chks:
    - name: replicasReady
      timeout: 600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: minio-scale-deployment
    type: scale
    namespace: ${GROUP.minio-resources.namespace}
    selectResource: deployment
    nameSelector: minio
  workflows:
  - name: backup
    sequence:
    - group: minio-resources
    - hook: minio-scale-deployment/down
    - hook: minio-scale-deployment/sync
    - group: minio-volumes
    - hook: minio-scale-deployment/up
    - hook: minio-scale-deployment/sync
  - name: restore
    sequence:
    - group: minio-volumes
    - group: minio-resources
    - hook: minio-deployment-check/replicasReady
